---
- hosts: 192.168.56.6
  become: true
  tasks:
   - name: install apache2 server
     apt:
       name: apche2
       state: present
   - name: start the service
     service:
       name: apache2
       state: started
   - name: copy files
     copy:
       src: index.html
       dest: /var/www/html/index.html
