---
- hosts: 192.168.56.2
  become: true
  tasks:
   - name: install httpd server
     yum:
       name: httpd
       state: present
   - name: start the service
     service:
       name: httpd
       state: restarted
   - name: copy files
     template:
       src: index.html
       dest: /var/www/html/index.html
